<?php

/**
 * Implements hook_simplesamlphp_auth_user_attributes().
 */
function tlu_h5p_simplesamlphp_auth_user_attributes(\Drupal\user\UserInterface $account, $attributes) {
  $updated = FALSE;
  $definitions = [
    'sn' => 'surname', // Surname
    'cn' => 'full_name', // Full name
    'givenName' => 'given_name', // First name
    'displayname' => 'display_name', //Display name (full name)
  ];
  $service = \Drupal::service('user.data');

  foreach ($definitions as $key => $field) {
    if (isset($attributes[$key]) && $attributes[$key]) {
      $service->set('tlu_h5p', $account->id(), $field, $attributes[$key][0]);
      $updated = TRUE;
    }
  }

  // Only set language preference on initial login
  if (isset($attributes['preferredLanguage']) && !$account->getLastAccessedTime()) {
    $language = $attributes['preferredLanguage'][0];
    $languages = \Drupal::languageManager()->getLanguages();

    if (array_key_exists($language, $languages)) {
      $account->set('langcode', $language);
      $account->set('preferred_langcode', $language);
      $updated = TRUE;
    }
  }

  if ($updated) {
    return $account;
  }

  return FALSE;
}

/**
 * Implements hook_user_format_name_alter().
 */
function tlu_h5p_user_format_name_alter(&$name, \Drupal\Core\Session\AccountInterface $account) {
  $full_name = \Drupal::service('user.data')->get('tlu_h5p', $account->id(), 'full_name');

  if ($full_name) {
    $name = $full_name;
  } else {
    $display_name = \Drupal::service('user.data')->get('tlu_h5p', $account->id(), 'display_name');

    if ($display_name) {
      $name = $display_name;
    }
  }
}

/**
 * Implements hook_preprocess_menu().
 */
function tlu_h5p_preprocess_menu(&$variables) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if (isset($variables['menu_name']) && $variables['menu_name'] === 'account') {
      if (isset($variables['items']['user.logout'])) {
        unset($variables['items']['user.logout']);
      }
    }
  }

  if (\Drupal::currentUser()->isAuthenticated()) {
    if (isset($variables['menu_name']) && $variables['menu_name'] === 'account') {
      if (isset($variables['items']['simplesamlphp_auth.saml_login'])) {
        unset($variables['items']['simplesamlphp_auth.saml_login']);
      }
    }
  }
}

/**
 * Implements hook_taxonomy_term_view().
 */
function tlu_h5p_taxonomy_term_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode === 'filter') {
    if (isset($build['name'])) {
      unset($build['name']);
    }
    if (isset($build['description'])) {
      unset($build['description']);
    }

    $build['filter_by_plain_text'] = [
      '#markup' => t('Materials for tag: <strong>@tag</strong>', [
        '@tag' => $entity->getName(),
      ]),
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tlu_h5p_form_node_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Disable revisions for materials
  if ($form_id === 'node_material_edit_form') {
    $form['revision_information']['#access'] = FALSE;
  }

  // Allow all users to change material publishing status
  if ($form_id === 'node_material_form' || $form_id === 'node_material_edit_form') {
    $form['status']['#access'] = TRUE;
  }
}
