<?php

/**
 * Implements hook_user_format_name_alter().
 */
function tlu_h5p_user_format_name_alter(&$name, \Drupal\Core\Session\AccountInterface $account) {
  $full_name = \Drupal::service('user.data')->get('openid_connect', $account->id(), 'oidc_name');

  if ($full_name) {
    $name = $full_name;
  }
}

/**
 * Implements hook_preprocess_menu().
 */
function tlu_h5p_preprocess_menu(&$variables) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if (isset($variables['menu_name']) && $variables['menu_name'] === 'account') {
      if (isset($variables['items']['user.logout'])) {
        unset($variables['items']['user.logout']);
      }
    }
  }
}

/**
 * Implements hook_taxonomy_term_view().
 */
function tlu_h5p_taxonomy_term_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode === 'filter') {
    if (isset($build['name'])) {
      unset($build['name']);
    }
    if (isset($build['description'])) {
      unset($build['description']);
    }

    $build['filter_by_plain_text'] = [
      '#markup' => t('Materials for tag: <strong>@tag</strong>', [
        '@tag' => $entity->getName(),
      ]),
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tlu_h5p_form_node_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Disable revisions for materials
  if ($form_id === 'node_material_edit_form') {
    $form['revision_information']['#access'] = FALSE;
  }

  // Allow all users to change material publishing status
  if ($form_id === 'node_material_form' || $form_id === 'node_material_edit_form') {
    $form['status']['#access'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function tlu_h5p_preprocess_node(&$variables) {
  if (!empty($variables['node']) && $variables['node']->getType() === 'material') {
    if (!$variables['node']->get('field_listed')->value) {
      $variables['attributes']['class'][] = 'material-unlisted';
    }
  }
}
